services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./contacts.db
    healthCheckPath: /health
